default: &DEFAULT

  # General
  verbose: True
  arch: 'dqfno'

  # FNO related
  dqfno:
    data_channels: 1
    modes: 
      - [16, 16]
      - [32, 32]
      - [8, 8]
    hidden_channels: 1
    n_layers: 4

  # Optimizer
  opt:
    n_epochs: 1
    learning_rate: 1e-3
    weight_decay: .01

  # Dataset related
  data:
    train_input_dir: /Users/anthonypoole/TACC/processed_data/test
    train_target_dir: /Users/anthonypoole/TACC/processed_data/test
    batch_size: 1

  # Losses
  losses:
    losses:
      - lp
      - h1
      - derived
    weights:
      - .4
      - .4
      - .2
  
