default: &DEFAULT

  # General
  verbose: True
  arch: dqfno
  device: cpu

  # FNO related
  dqfno:
    data_channels: 1
    modes:
      - [16, 16]
      - [32, 32]
      - [8, 8]
    hidden_channels: 8
    n_layers: 4
    derived_type: direct

  # Optimizer
  opt:
    n_epochs: 10
    learning_rate: 1e-3
    weight_decay: .01
    push_forward_type: only # none for no pushforward, only for only doing push forward testing and half for half way through training push forward

  # Dataset related
  data:
    train_input_dir: /Users/anthonypoole/data/local_dqfno/train/chunked
    train_target_dir: /Users/anthonypoole/data/local_dqfno/train/chunked
    test_input_dir: /Users/anthonypoole/data/local_dqfno/test/chunked
    test_target_dir: /Users/anthonypoole/data/local_dqfno/test/chunked
    push_forward_dir: /Users/anthonypoole/data/local_dqfno/train/ 
    push_forward_files: [fileone.h5, filetwo.h5]
    push_forward_steps: 4
    batch_size: 2

  # Losses
  losses:
    losses:
      - lp
      - h1
      - derived
    weights:
      - .4
      - .4
      - .2
