default: &DEFAULT

  # General
  verbose: True
  arch: 'dqfno'
  device: 'cpu'

  # FNO related
  dqfno:
    data_channels: 1
    modes:
      - [16, 16]
      - [32, 32]
      - [8, 8]
    hidden_channels: 1
    n_layers: 4
    derived_type: none

  # Optimizer
  opt:
    n_epochs: 10
    learning_rate: 1e-3
    weight_decay: .01

  # Dataset related
  data:
    train_input_dir: /Users/anthonypoole/data/local_dqfno/train/chunked
    train_target_dir: /Users/anthonypoole/data/local_dqfno/train/chunked
    test_input_dir: /Users/anthonypoole/data/local_dqfno/test/chunked
    test_target_dir: /Users/anthonypoole/data/local_dqfno/test/chunked
    batch_size: 4

  # Losses
  losses:
    losses:
      - lp
      - h1
      - derived
    weights:
      - .4
      - .4
      - .2
